### ISSUE TITLE
surplus 2.1.0 is unable handle comma-seperated local codes

### ISSUE THREAD

**Issue by markjoshwel** [markjoshwel/surplus#25]
```text
$ s+ -d WF8Q+WF, Praia
surplus version 2.1.0-local, debug mode (latest@future, Tue 05 Sep 2023 12:57:15 +0800)
debug: parse_query: behaviour.query=['WF8Q+WF,', 'Praia']
debug: split_query=['WF8Q+WF,', 'Praia']
debug: original_query='WF8Q+WF, Praia' <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
debug: cli: query=Result(value=StringQuery(query='WF8Q+WF, Praia'), error=None)
Traceback (most recent call last):
  File "/home/m/.cache/pypoetry/virtualenvs/surplus-CJ293Xyc-py3.11/bin/s+", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/m/works/surplus/surplus/surplus.py", line 1141, in cli
    print(f"error: {text.cry(string=not behaviour.debug)}", file=behaviour.stderr)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/works/surplus/surplus/surplus.py", line 253, in cry
    raise self.error
  File "/home/m/works/surplus/surplus/surplus.py", line 480, in to_lat_long_coord
    return Result[Latlong](geocoder(self.query))
                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/m/works/surplus/surplus/surplus.py", line 501, in default_geocoder
    raise NoSuitableLocationError(
surplus.surplus.NoSuitableLocationError: No suitable location could be geolocated from 'WF8Q+WF, Praia'
```

seems like an easy fix, strip words of commas when checking words for a partial plus code

**Comment by markjoshwel** [comment]
this is actually a regression from pre-2.0.0 releases

```text
$ s+ -d WF8Q+WF, Praia
surplus version 1.1.0, debug mode
debug: args.query='WF8Q+WF Praia'
debug: squery=['WF8Q+WF', 'Praia']
debug: lat=14.9173125, lon=-23.5113125
debug: location={...}
Biblioteca Nacional de Cabo Verde
Avenida Machado Santos, Chã d’Areia
7600
Cabo Verde
```

tested on both windows and alpine linux, seems like somewhere in the cli argument handling commas were just taken care of

**Comment by markjoshwel** [comment]
waiting for type-type conversion to be merged into future before branching off
