### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by markjoshwel** [markjoshwel/surplus#3]
```text
~ $ s+ 3RQ3+HW3 Pemping, Batam City, Riau Islands, Indonesia -d
surplus version 1.1.0, debug mode
debug: args.query='3RQ3+HW3 Pemping, Batam City, Riau Islands, Indonesia'
debug: squery=['3RQ3+HW3', 'Pemping', 'Batam', 'City', 'Riau', 'Islands', 'Indonesia']
debug: lat=1.0888875, lon=103.80479687500001
debug: location={'place_id': 248316196, 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'osm_type': 'way', 'osm_id': 691591389, 'lat': '1.090052', 'lon': '103.8061434', 'display_name': 'Batam, Kepulauan Riau, Indonesia', 'address': {'city': 'Batam', 'state': 'Kepulauan Riau', 'ISO3166-2-lvl4': 'ID-KR', 'country': 'Indonesia', 'country_code': 'id'}, 'boundingbox': ['1.0859358', '1.1078065', '103.7922105', '103.8084541']}
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/surplus", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/surplus.py", line 361, in cli
    result: tuple[bool, str] = surplus(query[-1], debug=args.debug)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/surplus.py", line 225, in surplus
    if location["address"].get("suburb", "")
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by shamsu07** [comment]
Is this issue still open??

**Comment by markjoshwel** [comment]
> Is this issue still open??

Yep, if I recall correctly all that needs to be done is just to handle for a None type.

**Comment by shamsu07** [comment]
Can I fix this?

**Comment by markjoshwel** [comment]
> Can I fix this?

Feel free.

**Comment by shamsu07** [comment]
I'm not able to push the code.

**Comment by markjoshwel** [comment]
Please fork the repository and open a pull request.
